# Generated by Django 3.2.3 on 2021-05-25 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_users_is_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
